version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'npm'
    directory: '/importer'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'npm'
    directory: '/templates'
    schedule:
      interval: 'monthly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
    assignees:
      - 'kajyr'
